-- Provision an Autonomous Database through Oracle's generated PL/SQL SDK.
--
-- This intentionally uses DBMS_CLOUD_OCI_DB_DATABASE rather than constructing
-- a REST URL, signed headers, or a JSON request body with DBMS_CLOUD.SEND_REQUEST.
-- OCI$RESOURCE_PRINCIPAL supplies the authentication. The dynamic group still
-- needs permission to manage autonomous-database-family in the target compartment
-- and to read the Vault secret used for the new database ADMIN password.
--
-- Prerequisites:
--   1. Run adbs_provision_grants.sql as ADMIN.
--   2. Run this script as DEMO_SALES (the function owner).
--
-- Check the generated SDK objects (run as ADMIN):
-- SELECT object_name, object_type, status
-- FROM all_objects
-- WHERE object_name IN (
--   'DBMS_CLOUD_OCI_DB_DATABASE',
--   'DBMS_CLOUD_OCI_DATABASE_CREATE_AUTONOMOUS_DATABASE_DETAILS_T',
--   'DBMS_CLOUD_OCI_DB_DATABASE_CREATE_AUTONOMOUS_DATABASE_RESPONSE_T'
-- )
-- ORDER BY object_name, object_type;

-- One-time, idempotent audit table. It records safe request-shape diagnostics
-- and typed SDK results, but never stores the Vault secret ID/value, wallet
-- material, or credentials.
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE demo_sales.provision_adbs_audit (
            audit_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_time      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            request_id        VARCHAR2(64) NOT NULL,
            region            VARCHAR2(64) NOT NULL,
            db_name           VARCHAR2(30) NOT NULL,
            workload          VARCHAR2(10) NOT NULL,
            storage_unit      VARCHAR2(2) NOT NULL,
            storage_value     NUMBER NOT NULL,
            http_status       NUMBER,
            request_payload   CLOB,
            response_payload  CLOB,
            response_headers  CLOB,
            error_message     VARCHAR2(4000)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Upgrade databases where a previous revision created the audit table without
-- the response_headers column.
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE demo_sales.provision_adbs_audit ADD (response_headers CLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

-- Inspect attempts from SQLcl:
-- SET LONG 1000000
-- SET LONGCHUNKSIZE 32767
-- SELECT audit_id, request_time, request_id, region, db_name, workload,
--        storage_value, storage_unit, http_status, error_message,
--        request_payload, response_headers, response_payload
-- FROM demo_sales.provision_adbs_audit
-- ORDER BY audit_id DESC
-- FETCH FIRST 20 ROWS ONLY;

CREATE OR REPLACE FUNCTION demo_sales.provision_adbs_tool (
    p_region              IN VARCHAR2,
    p_db_name             IN VARCHAR2,
    p_display_name        IN VARCHAR2,
    p_workload            IN VARCHAR2,  -- OLTP or DW
    p_ecpu_count          IN NUMBER,
    p_storage_tbs         IN NUMBER,    -- Quantity; retained name preserves existing callers.
    p_enable_data_guard   IN VARCHAR2,  -- YES or NO
    p_storage_unit        IN VARCHAR2 DEFAULT 'TB'  -- GB or TB
) RETURN CLOB
AUTHID CURRENT_USER
IS
    /*
      Set these to the only compartment and Vault secret this tool may use.
      The secret value is the new database ADMIN password. It is never read,
      logged, or returned by this function.
    */
    c_allowed_compartment_id   CONSTANT VARCHAR2(4000) :=
        'ocid1.compartment.oc1..aaaaaaaa6j6azlspv2u6b4v7tocylemhtbef5k3zft6lhmxgnpxacy6egc4a';
    c_admin_password_secret_id CONSTANT VARCHAR2(4000) :=
        'ocid1.vaultsecret.oc1.iad.amaaaaaaic2wo2qa3uqyuuxqtogk6wsu7vcr63mlwo5mbtpstlkxiiyrysfa';

    l_request DBMS_CLOUD_OCI_DATABASE_CREATE_AUTONOMOUS_DATABASE_DETAILS_T :=
        DBMS_CLOUD_OCI_DATABASE_CREATE_AUTONOMOUS_DATABASE_DETAILS_T();
    l_response DBMS_CLOUD_OCI_DB_DATABASE_CREATE_AUTONOMOUS_DATABASE_RESPONSE_T;
    l_result_json JSON_OBJECT_T := JSON_OBJECT_T();
    l_audit_json  JSON_OBJECT_T := JSON_OBJECT_T();
    l_workload     VARCHAR2(10) := UPPER(TRIM(p_workload));
    l_storage_unit VARCHAR2(2) := NVL(UPPER(TRIM(p_storage_unit)), 'TB');
    l_data_guard   NUMBER := CASE WHEN UPPER(TRIM(p_enable_data_guard)) = 'YES' THEN 1 ELSE 0 END;
    l_request_id   VARCHAR2(64) := RAWTOHEX(SYS_GUID());

    PROCEDURE log_provision_attempt(
        p_status   IN NUMBER,
        p_request  IN CLOB,
        p_response IN CLOB,
        p_headers  IN CLOB DEFAULT NULL,
        p_error    IN VARCHAR2 DEFAULT NULL
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO demo_sales.provision_adbs_audit (
            request_id, region, db_name, workload, storage_unit, storage_value,
            http_status, request_payload, response_payload, response_headers,
            error_message
        ) VALUES (
            l_request_id, LOWER(TRIM(p_region)), UPPER(TRIM(p_db_name)), l_workload,
            l_storage_unit, p_storage_tbs, p_status, p_request, p_response,
            p_headers, SUBSTR(p_error, 1, 4000)
        );
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            -- Audit failure must not mask an OCI SDK response or error.
    END log_provision_attempt;
BEGIN
    -- Guardrails constrain the request shape this agent can submit.
    IF NOT REGEXP_LIKE(LOWER(TRIM(p_region)), '^[a-z]+-[a-z]+-[0-9]+$') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid OCI region.');
    END IF;

    IF NOT REGEXP_LIKE(UPPER(TRIM(p_db_name)), '^[A-Z][A-Z0-9]{0,29}$') THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Database name must start with a letter and contain at most 30 alphanumeric characters.'
        );
    END IF;

    IF l_workload NOT IN ('OLTP', 'DW') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Workload must be OLTP or DW.');
    END IF;

    IF p_ecpu_count IS NULL OR p_ecpu_count <= 0
       OR p_storage_tbs IS NULL OR p_storage_tbs <= 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'ECPU count and storage must both be positive numbers.');
    END IF;

    IF l_storage_unit NOT IN ('GB', 'TB') THEN
        RAISE_APPLICATION_ERROR(-20006, 'Storage unit must be GB or TB.');
    END IF;

    IF UPPER(TRIM(p_enable_data_guard)) NOT IN ('YES', 'NO') THEN
        RAISE_APPLICATION_ERROR(-20009, 'Data Guard must be YES or NO.');
    END IF;

    -- ECPU OLTP accepts GB (minimum 20 GB); DW storage is expressed in TB.
    IF l_storage_unit = 'GB' AND l_workload <> 'OLTP' THEN
        RAISE_APPLICATION_ERROR(
            -20007,
            'GB storage is supported only for OLTP with the ECPU compute model; use TB for DW.'
        );
    END IF;

    IF l_storage_unit = 'GB' AND p_storage_tbs < 20 THEN
        RAISE_APPLICATION_ERROR(-20008, 'OLTP ECPU storage in GB must be at least 20 GB.');
    END IF;

    -- Build Oracle's generated SDK request object. No hand-written REST JSON.
    l_request.compartment_id := c_allowed_compartment_id;
    l_request.db_name := UPPER(TRIM(p_db_name));
    l_request.display_name := NVL(TRIM(p_display_name), UPPER(TRIM(p_db_name)));
    l_request.db_workload := l_workload;
    l_request.compute_model := 'ECPU';
    l_request.compute_count := p_ecpu_count;
    l_request.license_model := 'LICENSE_INCLUDED';
    l_request.is_auto_scaling_enabled := 0;
    l_request.is_local_data_guard_enabled := l_data_guard;
    l_request.secret_id := c_admin_password_secret_id;
    IF l_storage_unit = 'GB' THEN
        l_request.data_storage_size_in_g_bs := p_storage_tbs;
    ELSE
        l_request.data_storage_size_in_t_bs := p_storage_tbs;
    END IF;

    -- Safe, human-readable audit shape. Excludes compartment and secret IDs.
    l_audit_json.put('api', 'DBMS_CLOUD_OCI_DB_DATABASE.CREATE_AUTONOMOUS_DATABASE');
    l_audit_json.put('region', LOWER(TRIM(p_region)));
    l_audit_json.put('dbName', l_request.db_name);
    l_audit_json.put('displayName', l_request.display_name);
    l_audit_json.put('dbWorkload', l_request.db_workload);
    l_audit_json.put('computeModel', l_request.compute_model);
    l_audit_json.put('computeCount', l_request.compute_count);
    l_audit_json.put('storageUnit', l_storage_unit);
    l_audit_json.put('storageValue', p_storage_tbs);
    l_audit_json.put('isLocalDataGuardEnabled', l_data_guard);

    BEGIN
        l_response := DBMS_CLOUD_OCI_DB_DATABASE.CREATE_AUTONOMOUS_DATABASE(
            create_autonomous_database_details => l_request,
            opc_retry_token                   => l_request_id,
            opc_request_id                    => l_request_id,
            region                            => LOWER(TRIM(p_region)),
            credential_name                   => 'OCI$RESOURCE_PRINCIPAL'
        );

        -- The SDK response is typed. We intentionally return its stable
        -- transport metadata; the full resource can subsequently be retrieved
        -- with the typed GET/LIST API or the OCI CLI.
        l_result_json.put('result', 'CreateAutonomousDatabase submitted');
        l_result_json.put('api', 'DBMS_CLOUD_OCI_DB_DATABASE.CREATE_AUTONOMOUS_DATABASE');
        l_result_json.put('request_id', l_request_id);
        l_result_json.put('http_status', l_response.status_code);
        l_result_json.put('response_headers', l_response.headers);

        log_provision_attempt(
            l_response.status_code,
            l_audit_json.to_clob,
            l_result_json.to_clob,
            l_response.headers.to_clob
        );
        RETURN l_result_json.to_clob;
    EXCEPTION
        WHEN OTHERS THEN
            -- The generated client raises the OCI/PLSQL error directly. Unlike
            -- the old raw REST path, there is no session REST cache to query.
            log_provision_attempt(NULL, l_audit_json.to_clob, NULL, NULL, SQLERRM);
            RAISE;
    END;
END;
/
